# Generated by Django 2.1 on 2020-04-10 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('zmodyfikowano', models.DateTimeField(auto_now=True)),
                ('tresc', models.TextField()),
                ('plik_1', models.FileField(default='default.pdf', upload_to='upload_file/')),
                ('plik_2', models.FileField(default='default.pdf', upload_to='upload_file/')),
                ('plik_3', models.FileField(default='default.pdf', upload_to='upload_file/')),
                ('plik_4', models.FileField(default='default.pdf', upload_to='upload_file/')),
                ('zdjecie_1', models.ImageField(default='default.jpg', upload_to='upload_img/')),
                ('zdjecie_2', models.ImageField(default='default.jpg', upload_to='upload_img/')),
                ('zdjecie_3', models.ImageField(default='default.jpg', upload_to='upload_img/')),
                ('dodano', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Wstrzymane'), (1, 'Opublikowano')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadania_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dodano'],
            },
        ),
    ]
