# Generated by Django 2.1 on 2020-04-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdzian', '0002_auto_20200402_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dodano']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='dodano',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='tresc',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tytul',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='zmodyfikowano',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Wstrzymane'), (1, 'Opublikowano')], default=0),
        ),
    ]
