# Generated by Django 2.1 on 2020-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdzian', '0003_auto_20200402_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zdjecie_1',
            field=models.ImageField(default='default.jpg', upload_to='upload/'),
        ),
    ]
