# Generated by Django 2.1 on 2020-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdzian', '0004_post_zdjecie_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plik_1',
            field=models.ImageField(default='file.pdf', upload_to='upload_files/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zdjecie_1',
            field=models.ImageField(default='default.jpg', upload_to='upload_img/'),
        ),
    ]
