# Generated by Django 2.1 on 2020-04-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdzian', '0007_auto_20200403_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plik_2',
            field=models.FileField(default='default.pdf', upload_to='upload_file/'),
        ),
        migrations.AddField(
            model_name='post',
            name='plik_3',
            field=models.FileField(default='default.pdf', upload_to='upload_file/'),
        ),
        migrations.AddField(
            model_name='post',
            name='plik_4',
            field=models.FileField(default='default.pdf', upload_to='upload_file/'),
        ),
        migrations.AddField(
            model_name='post',
            name='zdjecie_2',
            field=models.ImageField(default='default.jpg', upload_to='upload_img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='zdjecie_3',
            field=models.ImageField(default='default.jpg', upload_to='upload_img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plik_1',
            field=models.FileField(default='default.pdf', upload_to='upload_file/'),
        ),
    ]
