# Generated by Django 2.1 on 2020-04-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdzian', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
