# Generated by Django 2.1 on 2020-04-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdzian', '0010_remove_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
