# Generated by Django 2.1 on 2020-04-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='autor',
        ),
    ]
